# SemVer: https://semver.org, generally {major.minor.patch}[-prerelease.{number}]+{mc_version}
# Fabric version ranges: https://www.npmjs.com/package/semver#ranges, list by split(',')
# Neo/Forge version ranges: https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html

# Project
mod_version=0.5.0
mod_group=dev.terminalmc
mod_id=flashside
mod_name=Flashside
mod_description=Moves the Flashback recording buttons to the side of the game menu.
mod_owner=TerminalMC
mod_authors=NotRyken
mod_contributors=
mod_translators=
mod_credits=
mod_license=Apache-2.0

# Links
homepage_url=https://modrinth.com/mod/JsjifJaW
sources_url=https://github.com/TerminalMC/Flashside
issues_url=https://github.com/TerminalMC/Flashside/issues
contact_url=https://terminalmc.dev

# Java
java_version=21
java_versions_fabric=>=21

# Minecraft
minecraft_version=1.21
minecraft_versions_fabric=>1.20.6 <1.22

# Parchment https://parchmentmc.org/docs/getting-started#choose-a-version
parchment_minecraft_version=1.21
parchment_version=2024.11.10

# Fabric https://fabricmc.net/develop
fabric_loader_version=0.16.10
fabric_loader_versions=>=0.16.8
fabric_api_version=0.102.0+1.21
fabric_api_versions=*

# Cloth Config https://modrinth.com/mod/9s6osm5g/versions
clothconfig_version=15.0.140
clothconfig_versions_fabric=>=15
clothconfig_versions_neoforge=[15,)

# ModMenu https://modrinth.com/mod/mOgUt4GM/versions
modmenu_version=11.0.3
modmenu_versions_fabric=>=11.0.0-beta.1

# Flashback https://modrinth.com/mod/4das1Fjq/versions
flashback_version=0.13.0
flashback_versions_fabric=>=0.11.0

# GitHub, Modrinth, CurseForge releases
# Plural properties expect CSV lists
github_repo=TerminalMC/Flashside
modrinth_id=JsjifJaW
curseforge_id=000000
curseforge_slug=aaaaaa
# 'STABLE', 'BETA' or 'ALPHA'
release_type=BETA
# Fabric
release_mod_loaders_fabric=fabric
release_game_versions_fabric=1.21,1.21.1
release_required_dep_ids_fabric_mr=4das1Fjq,P7dR8mSH,mOgUt4GM,9s6osm5g

# Mixin https://mvnrepository.com/artifact/org.spongepowered/mixin
mixin_version=0.8.7
# MixinExtras https://github.com/LlamaLad7/MixinExtras/releases
mixinextras_version=0.4.1
# MixinSquared https://github.com/Bawnorton/MixinSquared/releases
mixinsquared_version=0.2.0

# Plugins
# Fabric Loom https://mvnrepository.com/artifact/net.fabricmc/fabric-loom
loom_version=1.10.4
# Mod Publish Plugin https://plugins.gradle.org/plugin/me.modmuss50.mod-publish-plugin
mpp_version=0.8.4
# grgit-service https://github.com/ajoberstar/grgit/releases
grgitservice_version=5.3.0
# licenser https://plugins.gradle.org/plugin/org.cadixdev.licenser
licenser_version=0.6.1

# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
